export const CSS = String.raw`
.pgtsy-root{height:100%;overflow:auto;padding:14px 14px 22px;box-sizing:border-box;color:var(--dsw-text-primary,#e8e8ea);background:var(--dsw-bg-primary,transparent);font:13px/1.45 ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
.pgtsy-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;padding:2px 0 14px;border-bottom:1px solid var(--dsw-border,#2c2d31)}
.pgtsy-title{font-weight:650;font-size:15px;letter-spacing:.01em}.pgtsy-sub{margin-top:3px;color:var(--dsw-text-secondary,#979aa3);font-size:12px}
.pgtsy-state{display:inline-flex;align-items:center;gap:7px;border:1px solid var(--dsw-border,#34363c);border-radius:999px;padding:5px 9px;font-size:11px;font-weight:700;letter-spacing:.04em;white-space:nowrap}
.pgtsy-dot{width:7px;height:7px;border-radius:50%;background:#8a8d95}.pgtsy-state[data-state=NORMAL] .pgtsy-dot{background:#35b86b}.pgtsy-state[data-state=SHADOW] .pgtsy-dot{background:#4f91ff}.pgtsy-state[data-state=DEGRADED] .pgtsy-dot{background:#e4ad42}.pgtsy-state[data-state=SAFE_HOLD] .pgtsy-dot{background:#ee8f36}.pgtsy-state[data-state=HALTED] .pgtsy-dot{background:#ef5252}.pgtsy-state[data-state=OFFLINE] .pgtsy-dot{background:#7d8088}
.pgtsy-banner{margin:12px 0 0;padding:10px 11px;border:1px solid var(--dsw-border,#34363c);border-radius:9px;background:var(--dsw-bg-secondary,#191a1e)}.pgtsy-banner strong{display:block;margin-bottom:3px}.pgtsy-banner[data-state=SAFE_HOLD],.pgtsy-banner[data-state=HALTED]{border-color:#74462c}.pgtsy-banner[data-state=OFFLINE]{border-style:dashed}
.pgtsy-tabs{display:flex;gap:5px;margin:14px 0 10px;position:sticky;top:-14px;padding:8px 0;background:var(--dsw-bg-primary,#111216);z-index:3}.pgtsy-tab,.pgtsy-btn{appearance:none;border:1px solid var(--dsw-border,#34363c);background:var(--dsw-bg-secondary,#1a1b20);color:inherit;border-radius:7px;padding:6px 9px;font:inherit;cursor:pointer}.pgtsy-tab[aria-selected=true]{background:var(--dsw-bg-tertiary,#272931);font-weight:650}.pgtsy-btn:hover,.pgtsy-tab:hover{border-color:#555963}.pgtsy-btn:disabled{opacity:.45;cursor:not-allowed}
.pgtsy-section{margin-top:12px}.pgtsy-section>h3{margin:0 0 7px;color:var(--dsw-text-secondary,#9b9ea7);font-size:10px;text-transform:uppercase;letter-spacing:.13em;font-weight:700}
.pgtsy-card{border:1px solid var(--dsw-border,#2e3036);border-radius:9px;background:var(--dsw-bg-secondary,#18191d);overflow:hidden}.pgtsy-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;padding:8px 10px;border-top:1px solid var(--dsw-border,#292b30)}.pgtsy-row:first-child{border-top:0}.pgtsy-key{color:var(--dsw-text-secondary,#a0a3ac);min-width:0}.pgtsy-value{text-align:right;font-variant-numeric:tabular-nums;overflow-wrap:anywhere}.pgtsy-good{color:#54c77d}.pgtsy-warn{color:#e7ad4d}.pgtsy-bad{color:#ef7474}.pgtsy-muted{color:var(--dsw-text-secondary,#8e929c)}
.pgtsy-venue{padding:10px;border-top:1px solid var(--dsw-border,#292b30)}.pgtsy-venue:first-child{border-top:0}.pgtsy-venue-head{display:flex;justify-content:space-between;gap:10px;font-weight:650}.pgtsy-metrics{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px;margin-top:8px}.pgtsy-metric{padding:6px 7px;border-radius:6px;background:var(--dsw-bg-tertiary,#22242a)}.pgtsy-metric b{display:block;font-size:11px}.pgtsy-metric span{display:block;color:var(--dsw-text-secondary,#9296a0);font-size:10px;margin-top:2px}
.pgtsy-list{list-style:none;padding:0;margin:0}.pgtsy-list li{padding:9px 10px;border-top:1px solid var(--dsw-border,#292b30)}.pgtsy-list li:first-child{border-top:0}.pgtsy-line{display:flex;align-items:center;justify-content:space-between;gap:10px}.pgtsy-small{margin-top:3px;font-size:11px;color:var(--dsw-text-secondary,#9296a0)}
.pgtsy-events{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:11px}.pgtsy-event{display:grid;grid-template-columns:62px minmax(0,1fr);gap:8px;padding:7px 0;border-top:1px solid var(--dsw-border,#292b30)}.pgtsy-event:first-child{border-top:0}.pgtsy-event-time{color:var(--dsw-text-secondary,#8e929c)}.pgtsy-event-type{font-weight:700}.pgtsy-event[data-severity=critical] .pgtsy-event-type{color:#ef7474}.pgtsy-event[data-severity=warning] .pgtsy-event-type{color:#e7ad4d}
.pgtsy-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.pgtsy-error{margin-top:12px;color:#ef7474}.pgtsy-empty{padding:14px;color:var(--dsw-text-secondary,#9296a0);text-align:center}.pgtsy-foot{margin-top:16px;padding-top:12px;border-top:1px solid var(--dsw-border,#292b30);color:var(--dsw-text-secondary,#8e929c);font-size:10px}
`
